# Generated by Django 3.0.7 on 2020-06-13 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 16, 35, 43, 124203)),
        ),
    ]
